Hospital Management System/force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <description>Parent prescription to which this medication belongs.</description>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PREC-{0000}</displayFormat>
        <label>Prescription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hospital Management System/force-app/main/default/objects/Prescription__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Additional instructions or notes related to the prescription.</description>
    <label>Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Prescription__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Total amount of medicaitons</description>
    <label>Total Amount</label>
    <summarizedField>Medication__c.Line_Total__c</summarizedField>
    <summaryForeignKey>Medication__c.Prescription__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Prescription__c/fields/Total_Medication_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Medication_Amount__c</fullName>
    <description>Aggregated total of all medication line items
        associated with this prescription.</description>
    <label>Total Medication Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Hospital Management System/force-app/main/default/classes/PrescriptionService.cls
/*********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @ClassName:   PrescriptionService
 * @Description: This Class exposed the Prescription__c to REST API.
 *****************************************************************************************************/
@RestResource(urlMapping='/prescriptions/*')
public with sharing class PrescriptionService{
/*********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @MethodName:   getPrescriptions
 * @Description: This method queries the prescription from org.
 *****************************************************************************************************/
    @HttpGet
    global static List<Prescription__c> getPrescriptions(){
        return [SELECT
                    Id,Name,Total_Amount__c,Total_Medication_Amount__c,Notes__c,CreatedDate
                FROM
                    Prescription__c
                WITH
                    SECURITY_ENFORCED];
    }
}