Hospital Management System/force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>

    <label>Consultation</label>
    <pluralLabel>Consultations</pluralLabel>

    <nameField>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
        <displayFormat>CON-{0000}</displayFormat>
    </nameField>

    <sharingModel>ReadWrite</sharingModel>

    <description>
        Represents each consultation between a patient and a doctor.
        Stores visit dates, charges, follow-up information, and visit counts
        for clinical and billing purposes.
    </description>


</CustomObject>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <type>Date</type>
    <required>true</required>
    <description>
        Date on which the consultation occurred.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <type>Lookup</type>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <description>
        Doctor who conducted the consultation.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Next_Visit__c.field-meta.xml
<CustomField>
    <fullName>Next_Visit__c</fullName>
    <label>Next Visit</label>
    <type>Date</type>
    <description>
        Suggested follow-up consultation date.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <description>
        Patient involved in the consultation.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Visit_Charges__c.field-meta.xml
<CustomField>
    <fullName>Visit_Charges__c</fullName>
    <label>Visit Charges</label>
    <type>Currency</type>
    <precision>10</precision>
    <scale>2</scale>
    <description>
        Charges applied for the consultation.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/classes/ConsultationsService.cls
/*********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @ClassName:   ConsultationsService
 * @Description: This Class exposed the Consultation to REST API.
 *****************************************************************************************************/
@RestResource(urlMapping='/ConsultationsService/*')
global with sharing class ConsultationsService{
    @HttpGet
    global static List<Consultation__c> getConsultations(){
        return [SELECT 
                    Id,Name,Date_of_Visit__c,Doctor__c,Next_Visit__c,Patient__c,Visit_Charges__c
                FROM 
                    Consultation__c
                WITH 
                    SECURITY_ENFORCED];
    }
}