Hospital Management System/force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>

    <label>Consultation</label>
    <pluralLabel>Consultations</pluralLabel>

    <nameField>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
        <displayFormat>CON-{0000}</displayFormat>
    </nameField>

    <sharingModel>ReadWrite</sharingModel>

    <description>
        Represents each consultation between a patient and a doctor.
        Stores visit dates, charges, follow-up information, and visit counts
        for clinical and billing purposes.
    </description>


</CustomObject>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <type>Lookup</type>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <description>
        Doctor who conducted the consultation.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Consultation__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <description>
        Patient involved in the consultation.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Line-item level medication details belonging to a prescription.
Used for dosage tracking, pricing, and billing calculations.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hospital Management System/force-app/main/default/objects/Medication__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <description>Auto-calculated total cost for this medication line item.</description>
    <formula>Unit_Price__c * Quantity__c * Duration_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Medication__c/fields/Prescription__c.field-meta.xml
<CustomField>
    <fullName>Prescription__c</fullName>
    <description>Parent prescription to which this medication belongs.</description>
    <label>Prescription</label>
    <referenceTo>Prescription__c</referenceTo>
    <relationshipLabel>Medications</relationshipLabel>
    <relationshipName>Medications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Medication__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <description>Parent prescription to which this medication belongs.</description>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PREC-{0000}</displayFormat>
        <label>Prescription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hospital Management System/force-app/main/default/objects/Prescription__c/fields/Consultation__c.field-meta.xml
<CustomField>
    <fullName>Consultation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consultation during which this prescription was created.</description>
    <label>Consultation</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Prescription__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Total amount of medicaitons</description>
    <label>Total Amount</label>
    <summarizedField>Medication__c.Line_Total__c</summarizedField>
    <summaryForeignKey>Medication__c.Prescription__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Hospital Management System/force-app/main/default/classes/BillTriggerHandler.cls
public with sharing class BillTriggerHandler{
    private ApexPages.StandardController stdController;
    // Constructor to support Visualforce Extension
    public BillTriggerHandler(ApexPages.StandardController stdController){
        this.stdController=stdController;
    }
    // Action method invoked by the Visualforce page
    public void attemptEmail(){
        String sendEmailParam=ApexPages.currentPage().getParameters().get('sendEmail');
        if(sendEmailParam=='true'&&stdController.getId()!=null){
            sendBillEmail(new List<Id>{stdController.getId()});
        }
    }
    @AuraEnabled
    public static void sendBillEmail(List<Id> billIds){
        // Query Bill details and related Line Items
        List<Bill__c> bills=[SELECT 
                                    Id,Name,Billing_Date__c,Tax_Percentage__c,Sub_Total__c,Total_Amount__c,
                                    Patient__c,Patient__r.Name,Patient__r.PersonEmail,
                                    Consultation__c,Consultation__r.Name,Consultation__r.Doctor__r.Name,
                                    Prescription__c,Prescription__r.Name,
                                (SELECT 
                                        Name,Medication__c,Medication__r.Name,Unit_Price__c,Quantity__c,Line_Total__c 
                                    FROM 
                                        Bill_Line_Items__r)
                                FROM 
                                    Bill__c
                                WHERE 
                                    Id IN :billIds];

        List<Messaging.SingleEmailMessage> emails=new List<Messaging.SingleEmailMessage>();
        Map<Id,Blob> billPdfMap=new Map<Id,Blob>();
        List<ContentVersion> cvList=new List<ContentVersion>();
        List<Bill__c> billsWithPdf=new List<Bill__c>();
        // 1. Generate PDFs and Prepare ContentVersions
        for(Bill__c bill : bills){
            PageReference pdf=Page.BillPDF;
            pdf.getParameters().put('id',bill.Id);
            Blob pdfBlob;
            if(!Test.isRunningTest()){
                pdfBlob=pdf.getContentAsPDF();
            } else{
                pdfBlob=Blob.valueOf('Test PDF');
            }
            billPdfMap.put(bill.Id,pdfBlob);
            // Create ContentVersion
            ContentVersion cv=new ContentVersion();
            cv.Title='Invoice_'+bill.Name;
            cv.PathOnClient='Invoice_'+bill.Name+'.pdf';
            cv.VersionData=pdfBlob;
            cv.FirstPublishLocationId=bill.Id; // Automatically links to the Bill
            cvList.add(cv);
            billsWithPdf.add(bill);
        }
        // 2. Insert ContentVersions
        if(!cvList.isEmpty()){
            insert cvList;
        }
        // 3. Map Bill Id to ContentDocumentId
        // We use the list index to map back since cvList matches billsWithPdf order
        Map<Id,Id> cvIdToBillId=new Map<Id,Id>();
        for(Integer i=0; i < cvList.size(); i++){
            cvIdToBillId.put(cvList[i].Id,billsWithPdf[i].Id);
        }
        List<ContentVersion> insertedCVs=[SELECT
                                            Id,ContentDocumentId
                                        FROM
                                            ContentVersion
                                        WHERE
                                            Id
                                        IN
                                            :cvList];
        Map<Id,Id> billIdToContentDocId=new Map<Id,Id>();
        for(ContentVersion cv : insertedCVs){
            if(cvIdToBillId.containsKey(cv.Id)){
                billIdToContentDocId.put(cvIdToBillId.get(cv.Id),cv.ContentDocumentId);
            }
        }
        // 4. Create ContentDocumentLinks and Emails
        List<ContentDocumentLink> cdLinks=new List<ContentDocumentLink>();
        for(Bill__c bill : bills){
            Id contentDocId=billIdToContentDocId.get(bill.Id);
            // Link to Patient,Consultation,Prescription
            if(contentDocId!=null){
                Set<Id> linkedEntityIds=new Set<Id>();
                if(bill.Patient__c!=null) linkedEntityIds.add(bill.Patient__c);
                if(bill.Consultation__c!=null) linkedEntityIds.add(bill.Consultation__c);
                if(bill.Prescription__c!=null) linkedEntityIds.add(bill.Prescription__c);
                for(Id linkedId : linkedEntityIds){
                    ContentDocumentLink cdl=new ContentDocumentLink();
                    cdl.ContentDocumentId=contentDocId;
                    cdl.LinkedEntityId=linkedId;
                    cdl.ShareType='V'; // Viewer permission
                    cdl.Visibility='AllUsers';
                    cdLinks.add(cdl);
                }
            }
            // Prepare Email
            if(String.isNotBlank(bill.Patient__r.PersonEmail)&&billPdfMap.containsKey(bill.Id)){
                Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>{bill.Patient__r.PersonEmail});
                mail.setSubject('Invoice '+bill.Name+' - Hospital Management System');
                String body='Dear '+bill.Patient__r.Name+',\n\n';
                body+='We hope you are recovering well.\n\n';
                body+='Please find attached the invoice for your recent visit.\n';
                body+='--------------------------------------------------\n';
                body+='Bill Number: '+bill.Name+'\n';
                body+='Date: ' +(bill.Billing_Date__c!=null ? bill.Billing_Date__c.format() : '')+'\n';
                body+='Total Amount: '+bill.Total_Amount__c+'\n';
                body+='--------------------------------------------------\n\n';
                body+='If you have any questions regarding this bill,please contact our billing department.\n\n';
                body+='Regards,\nHospital Management System';
                mail.setPlainTextBody(body);
                Messaging.EmailFileAttachment attach=new Messaging.EmailFileAttachment();
                attach.setFileName('Invoice_'+bill.Name+'.pdf');
                attach.setBody(billPdfMap.get(bill.Id));
                mail.setFileAttachments(new List<Messaging.EmailFileAttachment>{attach});
                emails.add(mail);
            }
        }
        if(!cdLinks.isEmpty()){
            insert cdLinks;
        }
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }
}