Hospital Management System/force-app/main/default/objects/Doctor__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <type>Picklist</type>
    <description>
        Academic and professional medical degree held by the doctor.
    </description>
    <required>true</required>
    <valueSet>
        <valueSetDefinition>
            <value><fullName>MBBS</fullName><default>false</default></value>
            <value><fullName>MD</fullName><default>false</default></value>
            <value><fullName>BDS</fullName><default>false</default></value>
            <value><fullName>MS</fullName><default>false</default></value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Hospital Management System/force-app/main/default/objects/Doctor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
    <description>
        Official email address of the doctor used for communication and notifications.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/objects/Doctor__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <label>Mobile Number</label>
    <type>Phone</type>
    <description>
        Primary contact number of the doctor.
    </description>
    <required>true</required>
</CustomField>

Hospital Management System/force-app/main/default/classes/DoctorService.cls
/*********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @ClassName:   DoctorService
 * @Description: This Class exposed the Consultation to REST API.
 *****************************************************************************************************/
@RestResource(urlMapping='/DoctorService/*')
global with sharing class DoctorService{
/*********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @MethodName:   getDoctors
 * @Description: queries the doctors from org.
 *****************************************************************************************************/
    @HttpGet
    global static List<Doctor__c> getDoctors(){
        return [SELECT
                    Id,Name,Specialization__c,Degree__c,Email__c,Mobile_Number__c,Consultation_Fees__c
                FROM
                    Doctor__c
                WITH
                    SECURITY_ENFORCED];
    }
}