Hospital Management System/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Stores patient appointment records used for scheduling,
        doctor consultations, visit tracking, and operational reporting.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APT-{0000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hospital Management System/force-app/main/default/objects/Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <description>Scheduled date of the appointment.</description>
    <label>Appointment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Appointment__c/fields/Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Status__c</fullName>
    <description>Current lifecycle status of the appointment.</description>
    <label>Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Hospital Management System/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Doctor assigned to handle the appointment.</description>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient associated with this appointment.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Appointment__c/fields/Reason_for_Visit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Visit__c</fullName>
    <description>Detailed reason or symptoms provided by the patient for the visit.</description>
    <label>Reason for Visit</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Hospital Management System/force-app/main/default/objects/Doctor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
    <description>
        Official email address of the doctor used for communication and notifications.
    </description>
</CustomField>

Hospital Management System/force-app/main/default/classes/DoctorDashboardController.cls
/**********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @ClassName:   DoctorDashboardController
 * @Description: Controller for the doctor dashboard,providing a list of today's appointments.
 ****************************************************************************************************/
 public with sharing class DoctorDashboardController{
/**********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @ClassName:   AppointmentDetail
 * @Description: Wrapper class for the Appoinment details.
 *************************************************************************************************/
    public class AppointmentDetail{
        @AuraEnabled public String Id;
        @AuraEnabled public String Name;
        @AuraEnabled public String PatientName;
        @AuraEnabled public String ReasonForVisit;
        @AuraEnabled public String AppointmentStatus;
        @AuraEnabled public String FormattedTime;
    }
/**********************************************************************************************************
 * @Author:    CRM Team Innovation
 * @MethodName:   getTodayAppointments
 * @Description: This method queries the appointments for today and returns a list of AppointmentDetail objects.
 *               It also checks if the doctor is associated with the provided email address.
 *****************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<AppointmentDetail> getTodayAppointments(String email){
        try{
            if(String.isBlank(email)){
                throw new AuraHandledException('Email address is required.');
            }
            List<Doctor__c> doctors=[
                SELECT
                    Id 
                FROM
                    Doctor__c 
                WHERE
                    Email__c=:email 
                LIMIT 1];
            if(doctors.isEmpty()){
                AuraHandledException e=new AuraHandledException('Access Denied: No Doctor record associated with this email.');
                e.setMessage('Access Denied: No Doctor record associated with this email.');
                throw e;
            }
            Id doctorId=doctors[0].Id;
            // Query Appointments for Today(Removed Appointment_Time__c)
            List<Appointment__c> appointments=[
                SELECT
                    Id,Name,Patient__r.Name,Reason_for_Visit__c,Appointment_Status__c
                FROM
                    Appointment__c
                WHERE
                    Doctor__c=:doctorId
                AND
                    Appointment_Date__c=:System.today()
                AND
                    Appointment_Status__c != 'Cancelled'
                ORDER BY
                    Name ASC
                LIMIT 10];
            List<AppointmentDetail> results=new List<AppointmentDetail>();
            // Start time 9:00 AM
            Time slotTime=Time.newInstance(9,0,0,0);
            for(Appointment__c appt:appointments){
                AppointmentDetail detail=new AppointmentDetail();
                detail.Id=appt.Id;
                detail.Name=appt.Name;
                detail.PatientName=(appt.Patient__r != null)?appt.Patient__r.Name:'Unknown';
                detail.ReasonForVisit=appt.Reason_for_Visit__c;
                detail.AppointmentStatus=appt.Appointment_Status__c;
                // Create datetime instance to showcase time
                // 10 appointments from 9:00 AM to 7:00 PM -> 1 hour intervals
                DateTime dt=DateTime.newInstance(System.today(),slotTime);
                detail.FormattedTime=dt.format('h:mm a');
                results.add(detail);
                // Increment by 1 hour
                slotTime=slotTime.addHours(1);
            }
            return results;
        }catch(Exception e){
            throw new AuraHandledException('Error fetching appointments: '+e.getMessage());
        }
    }
}